# Site settings
url: "https://fazrabisco.com"
baseurl: "/html5up-forty"
markdown: kramdown
title: 
tagline: faz rabisco
bannerTitle: faz rabisco
bannerDescription: 

address: 
phone:
email:
twitter: username
facebook: username
instagram: username
github: username
linkedin: username
copyright: Copyright Owner